# Dependabot will run on day 25 of each month at 01:50 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "50 1 25 * *"
    open-pull-requests-limit: 15
    versioning-strategy: "increase"

  - package-ecosystem: "npm"
    directory: "/n8n-nodes-iobroker"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "50 1 25 * *"
    open-pull-requests-limit: 15
    versioning-strategy: "increase"

  - package-ecosystem: "npm"
    directory: "/src-iobroker"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "50 1 25 * *"
    open-pull-requests-limit: 15
    versioning-strategy: "increase"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "50 1 25 * *"
    open-pull-requests-limit: 15
